### ISSUE TITLE
information about complexes too one-dimensional

### ISSUE THREAD

**Issue by rwst** [PROconsortium/PRoteinOntology#169]
Species-unspecific protein complex concepts (from GO cell components) have more than the one dimension "species specific complex X"--->"is a"--->"species-unspecific complex Y". They also have "protein family Z"--->"part of"--->"species-unspecific complex Y". Example: the mad-max complex consists of a heterodimer of the bHLH-ZIP proteins Mad and Max (http://purl.obolibrary.org/obo/GO_0070443). This textual statement can be readily given in a computer-readable form by giving the protein families of Mad (http://purl.obolibrary.org/obo/PR_000025988) and Max (http://purl.obolibrary.org/obo/PR_000010211) as "part of" the complex. This useful information, even if too simplistic, is not readily available from the database.

**Comment by nataled** [comment]
Dear Mr. Stephan,
You're quite right that connections can be made between complexes and their components and, indeed, we do this for all complexes defined in PRO (see, for example, the human version of Mad/Max, http://purl.obolibrary.org/obo/PR_000025986). The lack of additional detail you note for the species-unspecific form is because (1) that term is not maintained by PRO, merely imported from GO; and (2) it is ontologically incorrect to assert that some protein is part of a complex. Rather, the assertion must be that the complex has, as a part, some protein. That's because a complex MUST have the indicated parts to be what it is, while a protein certainly exists in a form separate from a complex. Accordingly, we would not say http://purl.obolibrary.org/obo/PR_000025988 part of http://purl.obolibrary.org/obo/GO_0070443. It would have to be the other way around.

To my knowledge, the GO Consortium has not yet done this (@hdrabkin can you confirm?). For purposes of automated reasoning, we at PRO do have an interest in doing it on their behalf, but we currently lack the manpower. We are exploring some options in this regard.

**Comment by hdrabkin** [comment]
If I understand the question..

  1.  GO tries to define a generic complex (species indifferent) by it’s function
  2.  No indication of specific protein components other than in the text def or comment where an example may be given.
In GO if we wanted to have has_part pointing to a generic protein it would need to link to some generic term in PRO

**Comment by nataled** [comment]
Closing this ticket since no additional action can be taken by the PRO project beyond notifying GO curators of the concern (already done).
