### ISSUE TITLE
Need to explicitly handle sequence variants on the MSA view

### ISSUE THREAD

**Issue by Julie-Cowart** [PROconsortium/PRoteinOntology#191]
As a fork of issue #159 , now that variants are showing in the alignment view they need to be corrected to show the replacement amino acid in the view. Also the tooltip should be in a more readable format such as R133C or R->C 133 or something similar. Also a specific color for variants could be used instead of lumping it in with "other".

![Screen Shot 2020-07-16 at 4 28 10 PM](https://user-images.githubusercontent.com/25265446/87719510-77a17500-c781-11ea-95ff-c8f35e649a6c.png)
![Screen Shot 2020-07-16 at 4 28 19 PM](https://user-images.githubusercontent.com/25265446/87719519-7b34fc00-c781-11ea-9385-00bd9d372fe3.png)
![Screen Shot 2020-07-16 at 4 36 00 PM](https://user-images.githubusercontent.com/25265446/87720143-79b80380-c782-11ea-8412-2ffb347d60d1.png)

**Comment by Julie-Cowart** [comment]
It is now mostly implemented as discussed. Variants are highlighted in a different color and with a tooltip that show R-133-C meaning an R changed to C at residue 133 (e.g. https://proconsortium.org//app_test/entry/PR%3A000000364/). It needs testing.

**Comment by Julie-Cowart** [comment]
I have already found an issue with a term. https://proconsortium.org/app_test/entry/PR:B5B3R8/
It appears to represent a variant of a uniprot sequence and is labeled as such UniProtKB:P02662, Glu-99, CHEBI:29958|Glu-207, CHEBI:29947. However because it also has a uniprot id for its pro id the sequence that is pulled is that of UniProtKB:B5B3R8 instead of P02662 which already has those bases changed (and maybe other bases, I didn't check). This is fine for the alignment itself but the tooltips are wrong and instead of E 99 D and E 207 G it says D 99 D and G 207 G because the information about the existing base is missing. To fix this I could change the preference for which uniprot accession to fetch when there are two but I need to know how common is this case and if there are other cases where this might happen but the sequence we prefer is the one implied by the id rather than the one implied by the PRO-proteoform-std. It also just might be better for this term not to have the modifications in the definition at all since technically its definition (from a sequence standpoint) is that of B5B3R8.

**Comment by nataled** [comment]
There are other cases like this, but very few. These arise because UniProtKB is not fully curated, so there are TrEMBL entries (like B5B3R8) that are simply variants of Swiss-Prot entries (like P02662). We give priority to the accepted reference (SP) and define variants with respect to that sequence. Basically, what will happen in the future is the TrEMBL entry will end up being merged into the indicated SP entry and the identifier will be obsolete. I'm thinking that the source of the sequence should always be the PRO-proteoform-std if it exists, with the identifier (actually, the UniProtKB xref might be a better choice) as a fall-back. If that's done, then the tooltip will be correctly displayed. The reason the xref would be a better choice is because there are some cases where the term identifier is the UniProt type but the actual entry in UniProtKB has been removed. In all such cases there truly is no sequence, and the xref has been removed even if the PRO term identifier remains.

I'm not sure if this is related, but when I go to the parent entry (PR:P02662) the display gives only one sequence--the variant--and not the parent sequence or the SigPep- version. We might need to open another issue regarding cases where not all sequences are found, though I can't figure out why this one wouldn't be (given that the identifier and xref are provided).

**Comment by Julie-Cowart** [comment]
So I wrote a DB query there are only 12 cases with both a Uniprot xref and a proteoform being parsed from the def line and in all but 3 the uniprot ID matches (so order isn't important). The 3 that don't are
[PR:P0CE44](https://proconsortium.org/app/entry/PR:P0CE44)
[PR:A2AHT3](https://proconsortium.org/app/entry/PR:A2AHT3)
[PR:B5B3R8](https://proconsortium.org/app/entry/PR:B5B3R8)

I swapped the order to prefer the accession that the proteoform is in reference to over the xref and it rescued these 3 terms msa view and that of their parents (see test site vs production).

**Comment by nataled** [comment]
Great! Yeah, I checked and these are all cases of the sort described earlier. If you agree, I think this issue can be closed...

**Comment by Julie-Cowart** [comment]
pushed to production
