### ISSUE TITLE
Term issue: AP4 [trans-Golgi network membrane]

### ISSUE THREAD

**Issue by nicolevasilevsky** [PROconsortium/PRoteinOntology#196]
Proposed new term: AP4 [trans-Golgi network membrane]
Synonyms: AP4 complex, AP4 heterotetramer, Adaptor protein complex 4

Related: https://reactome.org/content/detail/R-HSA-5229123

Needed for: https://github.com/monarch-initiative/mondo/issues/1729

**Comment by nataled** [comment]
Hi Nicole,

I have created the following three terms. The first is a generic AP4 that can be used for any organism. I made this on the basis of the fact that such complexes are found in multiple organisms, as indicated by Reactome. The second is specific to human, which is presumably what you're most interested in. The third was created after reading the associated MONDO request. This can basically be used for drilling down to underlying cause. Please let me know the identifier that will be used for that request so that I can reference it in the comment to PR:000050390.

The requested term(s) can be referenced immediately, and the PURLs will resolve, but will not be available within the main OWL file until next release (we just had one two weeks ago, so another isn't on the immediate horizon). That means you would not be able to search for it on the PRO or other web site, and it won't appear in the hierarchy. Nonetheless, it is in the interim (development) file, available at http://purl.obolibrary.org/obo/pr/pr-dev.obo.

[Term]
id: PR:000050388
name: adaptor protein complex 4
def: "A protein-containing complex that is a heterotetramer of AP-4 complex subunits beta-1, epsilon-1, mu-1, and sigma-1." [PRO:DAN, Reactome:R-HSA-5229123, PMID:11598180]
comment: Category=complex. Requested by=MONDO.
synonym: "AP4" EXACT PRO-short-label [PRO:DAN]
synonym: "AP4 complex" EXACT [Reactome:R-HSA-5229123]
synonym: "AP-4 complex" EXACT [PRO:DAN]
synonym: "AP4 heterotetramer" EXACT [Reactome:R-HSA-5229123]
is_a: GO:0032991 ! protein-containing complex
relationship: has_component PR:000004111 {cardinality="1"} ! AP-4 complex subunit beta-1
relationship: has_component PR:000004112 {cardinality="1"} ! AP-4 complex subunit epsilon-1
relationship: has_component PR:000004113 {cardinality="1"} ! AP-4 complex subunit mu-1
relationship: has_component PR:000004114 {cardinality="1"} ! AP-4 complex subunit sigma-1

[Term]
id: PR:000050389
name: adaptor protein complex 4 (human)
def: "A protein-containing complex that is a heterotetramer of AP-4 complex subunits beta-1, epsilon-1, mu-1, and sigma-1 in human." [PRO:DAN, Reactome:R-HSA-5229123, PMID:11598180]
comment: Category=organism-complex. Requested by=MONDO.
synonym: "hAP4" EXACT PRO-short-label [PRO:DAN]
synonym: "AP4 complex (human)" EXACT [Reactome:R-HSA-5229123]
synonym: "AP-4 complex (human)" EXACT [PRO:DAN]
synonym: "AP4 heterotetramer (human)" EXACT [Reactome:R-HSA-5229123]
xref: Reactome:R-HSA-5229123 "PR:000050389 located_in GO:0032588"
is_a: GO:0032991 ! protein-containing complex
relationship: has_component PR:Q9Y6B7 {cardinality="1"} ! AP-4 complex subunit beta-1 (human)
relationship: has_component PR:Q9UPM8 {cardinality="1"} ! AP-4 complex subunit epsilon-1 (human)
relationship: has_component PR:O00189 {cardinality="1"} ! AP-4 complex subunit mu-1 (human)
relationship: has_component PR:Q9Y587 {cardinality="1"} ! AP-4 complex subunit sigma-1 (human)

[Term]
id: PR:000050390
name: adaptor protein complex 4 component
def: "A protein that is a component of adaptor protein complex 4." [PRO:DAN]
comment: Category=union. Note: Defects in any of these contribute to any of the AP-4 deficiency syndromes, including hereditary spastic paraplegia (DOID:2476), due to failure to form functional adaptor protein complex 4 [https://www.ncbi.nlm.nih.gov/books/NBK535153].
synonym: "hAP4component" EXACT PRO-short-label [PRO:DAN]
is_a: PR:000000001 ! protein
union_of: PR:Q9Y6B7 ! AP-4 complex subunit beta-1 (human)
union_of: PR:Q9UPM8 ! AP-4 complex subunit epsilon-1 (human)
union_of: PR:O00189 ! AP-4 complex subunit mu-1 (human)
union_of: PR:Q9Y587 ! AP-4 complex subunit sigma-1 (human)

**Comment by nataled** [comment]
Oops, never mind about the identifier, it's right there in the request! Also, I should point out that the PRO term does not have location indicated as the Reactome entry does (except as a note in the xref). Will close this ticket, but please reopen if I missed something.

**Comment by nicolevasilevsky** [comment]
Wow, thanks for the quick reply @nataled! I appreciate it. :)
