### ISSUE TITLE
Add preferred roots to make using pro easier in OLS

### ISSUE THREAD

**Issue by matentzn** [PROconsortium/PRoteinOntology#213]
Right now its quite hard to find an entry point into pro from the default tree view in OLS:
https://www.ebi.ac.uk/ols/ontologies/pr

Preferred roots are a new way of tagging those classes which constitute the actual _roots_ of your domain (say protein and protein-protein complex). 

You can see preferred roots in action for mondo here: https://www.ebi.ac.uk/ols/ontologies/mondo

The corresponding (OBO format) annotations are:

```
property_value: IAO:0000700 MONDO:0000001
property_value: IAO:0000700 MONDO:0021125
property_value: IAO:0000700 MONDO:0042489
```

which are all annotation assertion axioms on the owl ontology itself, aka Ontology Annotations.

**Comment by nataled** [comment]
I see what you mean! I see three problems:

1) The bulk of PRO is buried under BFO. There was a time some years ago where the Foundry recommended doing this. Not all ontologies complied, but PRO did. I never much liked it (COB will help with this). In the meantime, this problem will be fixed by the solution you propose (already implemented internally; will appear with next release that is in progress).

2) Most of the terms visible by default are from other ontologies. A few are fine, but not the GO molecular function terms. This problem stems from a bug in our import processing (which pre-dates ROBOT and OntoFox and MIREOT). I'm attempting a temporary fix, but in the future ROBOT will be used for this.

3) OLS appears to have a bug as well, though I'm not fully certain. I can tell that some PRO terms are appearing directly under root even though they are very definitely within the proper hierarchy otherwise. All such cases are those that involve logical definitions that state a cardinality. It seems that OLS ignores the parent when displaying the hierarchy, even though it shows the parent under 'Equivalent to' section. See "osteocalcin peptide, fully carboyxylated form" for an example. I checked Ontobee and BioPortal; the misbehavior appears to be unique to OLS. I cannot determine if this is due to some difference in loaded file (OBO vs OWL, or reasoned vs non-reasoned). The IRI indicates reasoned OWL, but then they include OBO-ish information too.

**Comment by matentzn** [comment]
Very interesting @nataled All sounds great!

If you can see a bug like that, just make a ticket to that https://github.com/EBISPOT/OLS/issues

The hierarchy they render should reflect exactly what Protege would show - if not, I would think there is a bug.

Thanks for the prompt response :)

**Comment by nataled** [comment]
Bug submitted to OLS: https://github.com/EBISPOT/OLS/issues/442

**Comment by nataled** [comment]
OLS bug fixed. Will need to await next PRO release to verify that the 'preferred root' solution implemented has worked (new release coming next week).

**Comment by matentzn** [comment]
Very cool!

**Comment by nataled** [comment]
Success!
