### ISSUE TITLE
Rogue punctuation in links

### ISSUE THREAD

**Issue by nataled** [PROconsortium/PRoteinOntology#234]
Using this example: https://proconsortium.org/app/entry/PR:000037679/

It appears that the period at the end of each definition sentence is included in the link (one to UniProtKB and the other to CHEBI). The same is true for the link in the comment.

**Comment by Julie-Cowart** [comment]
Fixed on test server. Side effect is ids with . in them are not allowed (but I'm not sure that there are any).

**Comment by nataled** [comment]
There are many, actually. Mostly these are genes from pombe and zebrafish. It appears that you applied the fix globally, but it is only needed for the definition line and comment. For each of these, ignore the period if that period is either at the end of the line, is followed by a space, or is followed by quotation marks. Can probably just ignore the period for links when the period is followed by any non-word character. That latter fix would probably work globally as well.

**Comment by Julie-Cowart** [comment]
The code for adding links to things that look like ids is global except for the protein forms table since that is done on the client side (in javascript) rather than the server side(in python) but i have added a lookahead to make sure the next char isn't a word character and that seems to handle the above case and pombe gene templates. 

So while I'm fixing this can we review id rules. Ids cannot contain these characters | ; , [ ] { } ~ or whitespace since these are all separators that might be used in a definition line. We specifically do have ids with numbers, letters, '.' (Pombase), '_' (UniProtKB_VAR) and '-' (UniProtKB) but the '.' can't be at the end (since then we can't tell if it is the end of a sentence or part of the id). The ':' joins the prefix and the id but I don't think is allowed in the id itself. Any other special characters in ids I should know about?

**Comment by nataled** [comment]
Currently the only characters used in the local id (part after the colon) that aren't letters or numbers are the ones you mentioned: period, dash, underscore.

**Comment by Julie-Cowart** [comment]
this is fixed and in production
