### ISSUE TITLE
PR:000000164 discrepency?

### ISSUE THREAD

**Issue by wmmounts** [PROconsortium/PRoteinOntology#264]
Hello,

For BMP2 (PR:000000164), I've noticed that the UI gives the following for 'Show OBO stanza'.

[Term]
id: PR:000000164
**name: bone morphogenetic protein 2**
**def: "A bone morphogenetic protein that is a translation product of the human BMP2 gene or a 1:1 ortholog thereof." [PRO:CNA]**
comment: Category=gene.
**synonym: "BMP2" EXACT PRO-short-label [PRO:DAN]**
synonym: "BMP-2" EXACT []
synonym: "BMP2A" RELATED Gene-based []
synonym: "BMP-2A" EXACT []
synonym: "bone morphogenetic protein 2A" EXACT []
xref: PANTHER:PTHR11848:SF50
is_a: PR:000000034 ! bone morphogenetic protein

However, when I go to use the obo files in another application, the OBO stanza in either pro_reasoned or pro_nonreasoned shows the following.

[Term]
id: PR:000000164
**name: BMP2**
**def: "A BMP that is a translation product of the human BMP2 gene or a 1:1 ortholog thereof." [PRO:CNA]**
comment: Category=gene.
synonym: "BMP-2" EXACT []
synonym: "BMP2A" RELATED Gene-based []
synonym: "BMP-2A" EXACT []
synonym: "bone morphogenetic protein 2A" EXACT []
xref: PANTHER:PTHR11848:SF50
is_a: PR:000000034 ! BMP

Where is the web UI getting the stanza that includes name: bone morphogenetic protein 2?  When I leverage the obo files directly, I'm losing this term/synonym.

Thank you.

**Comment by nataled** [comment]
Dear @wmmounts,

Thank you for your issue submission. The answer to your direct question pertaining to where the web UI is getting the stanza when you click 'Show OBO stanza' is that it comes directly from the PRO database. An explanation: the ontology information, in order to make it quickly searchable and to integrate the ontology with other applications, is also loaded into a database at the time of new release. This includes the full stanza. So clicking on the show stanza link grabs it from there. It will always be the most-current version.

I looked into what could cause the difference. My first suspicion was that it is a versioning issue. This proved correct, as the current version (64.0, at least for the next day or so until 65.0 comes out) includes the spelled-out name and the PRO-short-label synonym 'BMP2'. However, the previous release, 63.0, lacks these, and the stanza looks exactly as you have noted. I confirmed that a download of the current release, 64.0, from the PRO website also contains the name and synonym. So that means either (a) you're using a version downloaded prior to September of this year or (b) the website from which you've downloaded the files (or the application you're using) still carries the previous version as 'current' (even though it isn't). The piece of information I'm missing is which other application you are using; I'd need to confirm that the version from that application or web site is indeed an old one.

Best regards,
Darren Natale

P.S. To ensure that you are always getting the latest version, you can use this link http://purl.obolibrary.org/obo/pr.obo for the reasoned version (the default version), or this http://purl.obolibrary.org/obo/pr-asserted.obo for the non-reasoned version. See the page http://purl.obolibrary.org/obo/pr/purls for links to other files (including past releases).

**Comment by wmmounts** [comment]
Hi Darren,

Thanks very much for taking the time to respond.  It’s very much appreciated.

I retrieved the files that I was using from here: (https://proconsortium.org/download/current/).  The files there have date stamps on or around Sept 6, and the pro_release_note.txt file identified the data as v63.0 this week.  This is where I accessed pro_reasoned.obo and pro_nonreasoned.obo with the structure containing “name: BMP2”.  Now that I’ve said all of this, I’ve now used the link you provided (http://purl.obolibrary.org/obo/pr.obo), and I get to the exact same URL I was, only now the data reference v64.0 and the record with “name: bone morphogenetic protein 2”.

None of this really make sense to me as I’ve only been working on this this week, and the obo files I’ve downloaded are v63.0 and came from the above sites.  I have no explanation given the timestamps on the file appear to be unchanged and are now showing me v64.0 files.  I can confirm that the most recently downloaded copy of https://proconsortium.org/download/current/pro_reasoned.obo, gives me a file from v64.0.

The third party application I’m supporting almost certainly has v63.0 loaded, and we’ll update to v64.0 (or v65.0) soon.

Sorry to trouble you with a version question and that the above information is somewhat nonsensical.  I have no explanation for how I could have retrieved v63.0 files from the proconsortium.org webserver.

Regards,
Bill

**Comment by nataled** [comment]
Very strange indeed! As you surmised, the link I provided does indeed resolve to the file located in /current/ (which itself is actually a pointer to the files in /release_64.0/). 

Just for your information, we intend to upload release 65.0 tomorrow (Friday) at about noon. You might discover a datestamp discrepancy, but just know that we 'touch' the dates to be the same as the date the OWL file was generated (which was the 13th, I believe).

Out of curiosity, what is the third party application you refer to?

**Comment by wmmounts** [comment]
Dear Darren,

Apologies, but I’m bound by confidentiality, and cannot disclose the third-party application.

I see that release 65 is out.  Thanks for yours and the team’s continued efforts.  Upon querying proconsortium.org, I’m receiving error messages, FYI.  For the following URL: https://proconsortium.org/app/entry/PR:000000164/, I’m receiving the following:

***@***.***

Best regards,
Bill

**Comment by nataled** [comment]
I understand about the confidentiality, no problem.

As for the error, we've been experiencing intermittent problems. It's currently working again.

**Comment by wmmounts** [comment]
Much appreciated.

One last comment.  The third-party uses EBI OLS as their source for many ontologies.  In my review, the current OLS page for Protein Ontology (https://www.ebi.ac.uk/ols/ontologies/pr) appears to be referencing or pointing to both release 64.0 and release 65.0.  Under Ontology information, Ontology IRI points to the current release (65.0), but Version IRI is still pointing to release 64.0.  The last loaded date may suggest that release 65.0 was identified and processed.  However, date=03:09:2021 19:50 is a direct reference to release 64.0.

I have submitted a question here: https://elixir-europe.org/platforms/interoperability/enquiry-form, but I’m not certain if this is the best route for the issue that I think I’m seeing.  If you agree with what I’m seeing and have contacts at EBI, you may want to reach out to them.

Best regards and happy holidays!
Bill

**Comment by nataled** [comment]
Thanks for alerting me to that problem. I've verified that the correct version IRI is at least specified in the files themselves, so it looks like a failure on the part of OLS to update the version line on the web. I do have contacts at EBI and will reach out to them.

Best regards and happy holidays to you!

**Comment by nataled** [comment]
I submitted a ticket to the OLS tracker. I realize that their last load of PRO was on the 15th. On that day, release 64.0 was indeed the version available, as 65.0 wasn't uploaded until the 17th. 

Wow, as I was typing this, OLS already got back to me. It seems that they update nightly from Sunday to Thursday, so that if there's a failure it will happen on a work day. Makes sense. But, that also means that they should have updated anyway a few days ago. Here's where something else comes into play: due to the holidays, OLS has frozen any updates until the 3rd of January. All will be fine thereafter.
