### ISSUE TITLE
Add mechanism to display PRO GPI for single term on web

### ISSUE THREAD

**Issue by nataled** [PROconsortium/PRoteinOntology#292]
like is done for 'Show OBO stanza'

**Comment by Julie-Cowart** [comment]
This is live on the test site. 

It parses out the top part of the header and the matching line(s) from the file at https://proconsortium.org/download/more/pro.gpi so it will automatically support new releases. By the way the header claims it was generated 2020-12-11 so it might need updating (the file or maybe just the header).

Do all terms have a GPI entry? If only certain types of terms have it we can suppress the link on the enry page. We do this with PAF so that only pages with PAF have the link (not done for OBO since all entries have this).

**Comment by nataled** [comment]
Not all terms have a GPI. The term must be associated with an NCBITaxon ID and, conversely, all terms with such ID is represented. That means that you can directly ignore such terms, or you can go with a "if I can't find it in the file" method. By the way, the file you want to use is https://proconsortium.org/download/development/pro_wv.gpi (the other one is updated at release time only).

**Comment by Julie-Cowart** [comment]
Ok I have added a check for entries that have a taxon id (i.e. organism specific) and otherwise the link to GPI will be suppressed on the entry page. I can't check if the grep produces the result as the check because that doesn't happen until after the link is clicked and a new request for the actual GPI file is submitted.

I hesitate to point to the development version of the gpi file since then we can't test during prerelease on the test page. Alternatively, we may need to modify the prerelease process to include the gpi file so the test site can be linked to that.

**Comment by Julie-Cowart** [comment]
pushed to production site
