### ISSUE TITLE
Term issue: hhf1 hhf2 hhf3 H4K20me2 modified

### ISSUE THREAD

**Issue by ValWood** [PROconsortium/PRoteinOntology#301]
P09322
hhf1 hhf2 hhf3
H4K20me2 modified
(we already have H4K20me3 )

PMID:17190600 crb1 binds H4K20me2 but not H4K20me3

**Comment by nataled** [comment]
Hi Val,
Did you want a single term that represents **_any_** histone H4 K20 dimethylated? We already have the terms for each of the specific genes given:
hhf1 H4K20me1 PR:000050529
hhf1 H4K20me2 PR:000050530
hhf1 H4K20me3 PR:000050531
hhf2 H4K20me1 PR:000050532
hhf2 H4K20me2 PR:000050533
hhf2 H4K20me3 PR:000050534
hhf3 H4K20me1 PR:000050535
hhf3 H4K20me2 PR:000050536
hhf3 H4K20me3 PR:000050537

**Comment by ValWood** [comment]
Sorry, I tried to look. This is all I need
Remind me again  where I can search with a uniProt Id, I can never find it!

**Comment by nataled** [comment]
At https://proconsortium.org/ (image attached)

![Untitled](https://user-images.githubusercontent.com/13770634/219116662-881af80c-2175-4361-90db-c70cf32ef640.png)

**Comment by ValWood** [comment]
Right, the search box was off the right of my screen and I was going to the magnifying glass link, I  don't think you can search UniPRot IDs there. Anyway, hopefully I will remember this time. I think this is  like the 3rd time I asked?

**Comment by nataled** [comment]
I believe that's accurate :)

I'm not sure what you mean by 'the magnifying glass link' unless you refer to the one in the top banner? I question whether that's the one you refer to it because it would have been off screen too (because it is even further to the right than the top banner search box). Also, the link itself goes to the main search page, where the needed search can be done as well.

But, this is actually good feedback. You are apparently forced to scroll right to see some rather important functionalities. Unless...you just had the window partially off screen? The fact that this has recurred makes me think the problem is inherent to our site. Please let me know if it is the site design. If so, I'll have us think about revising.

**Comment by ValWood** [comment]
Actually if my book mark was the front page I would have found it, but for some reason, my bookmark was set to here
https://proconsortium.org/app/entry/PR%3A000027551/
So I was only seeing the menu bar and not the search box. (this page is very wide)

**Comment by nataled** [comment]
Oh so is the magnifying glass icon you mentioned the one for a close-up look at sequences? That is, associated with the Interactive Sequence View panel?

**Comment by ValWood** [comment]
<img width="162" alt="Screenshot 2023-02-15 at 20 19 00" src="https://user-images.githubusercontent.com/7359272/219144058-3c35c3de-bb51-46b8-b862-8829f82b5c95.png">

**Comment by nataled** [comment]
That should work. The link goes to the main search page and retrieval page. For what you wanted to do, you'd use the second panel "Text Search".
