### ISSUE TITLE
Term issue:  Request to add terms to PRO

### ISSUE THREAD

**Issue by Astghik-S** [PROconsortium/PRoteinOntology#338]
Dear PRO Maintainers,

As part of the OBO Foundry principles, we aim to ensure that terms are included in the most appropriate ontology and avoid duplication across ontologies wherever possible. We are working on a biomarker ontology (BMONT) and have identified several terms related to clinical and diagnostic metrics that may align well with the scope of PRO. Before proceeding to define these terms in our ontology, I wanted to reach out to ask if you would like to integrate any or all of the following terms into PRO.

The terms are as follows:

-  lipoprotein a
-  fibrinogen
-  Creatine Kinase-MB

We believe they could add value to PRO if they are not already included.

Please let us know if you would like to incorporate any of these terms, or if you would prefer that we proceed with defining them in our own ontology. We are happy to collaborate and ensure these terms are defined in a way that aligns with OBO Foundry standards.

Thank you for considering our request. We look forward to hearing your thoughts and are open to any guidance you may have.

Best regards,
Astghik Sargsyan
Fraunhofer Institute for Algorithms and Scientific Computing SCAI

**Comment by nataled** [comment]
Dear @Astghik-S,
Thank you for your request. We will take a closer look, but at first glance it seems that lipoprotein a could be included. Both fibrinogen and Creatine Kinase-MB are already in PRO or GO, though you would need to verify that the terms as given correlate with your needs:

GO:0005577 (http://purl.obolibrary.org/obo/GO_0005577) fibrinogen complex
PR:000050466 (http://purl.obolibrary.org/obo/PR_000050466) fibrinogen complex (human)
PR:000027247 (http://purl.obolibrary.org/obo/PR_000027247) cytosolic creatine kinase complex, MB-type
PR:000050356 (http://purl.obolibrary.org/obo/PR_000050356) cytosolic creatine kinase complex, MB-type (human)

Please note that there are related creatine kinase terms in PRO, so these should be reviewed as well, in case another fits your needs better than the ones indicated. 

Best regards,
Darren

**Comment by Astghik-S** [comment]
Dear @nataled,
Thank you for your quick reply. I understand that fibrinogen is already represented in existing ontologies, but I have some concerns about reusing these terms given the distinctions in biomarker contexts.

In particular, I aim to represent both fibrinogen and fibrinogen complex as distinct entities within my ontology. In clinical biomarker applications, these entities carry different implications: fibrinogen typically refers to the soluble plasma protein measured in routine assessments for inflammation or cardiovascular risk, while fibrinogen complex often denotes aggregates or bound states relevant to clot formation and thrombotic risk.

I would appreciate hearing your perspective on this approach.

Best regards,
Astghik

**Comment by nataled** [comment]
Dear Astghik,

Fibrinogen--the soluble plasma protein--is a complex, hence the name (PRO simply followed GO's nomenclature). That is, so far as I can tell, they are synonyms. What you are referring to as 'fibrinogen complex' seems to be fibrin(?), the clotting factor derived from processing of fibrinogen. I did see something else called 'fibrinogen complex' which appears to be a mixture of many proteins but chiefly fibrinogen. As it is a mixture of proteins and not a single entity, that latter usage would not be in scope for PRO.

I am unclear as to the distinctions you need regarding the other two requested terms. Can you provide a bit more information on these?

Best regards,
Darren

**Comment by nataled** [comment]
Following up on lipoprotein(a)...this is in scope for PRO, as it is a complex of apolipoprotein a and apolipoprotein B-100. Do you need a human-specific version, or only something generic (to any species)?

**Comment by Astghik-S** [comment]
> Following up on lipoprotein(a)...this is in scope for PRO, as it is a complex of apolipoprotein a and apolipoprotein B-100. Do you need a human-specific version, or only something generic (to any species)?

Yes, human-specific is enough in this case

**Comment by Astghik-S** [comment]
> Dear Astghik,
> 
> Fibrinogen--the soluble plasma protein--is a complex, hence the name (PRO simply followed GO's nomenclature). That is, so far as I can tell, they are synonyms. What you are referring to as 'fibrinogen complex' seems to be fibrin(?), the clotting factor derived from processing of fibrinogen. I did see something else called 'fibrinogen complex' which appears to be a mixture of many proteins but chiefly fibrinogen. As it is a mixture of proteins and not a single entity, that latter usage would not be in scope for PRO.
> 
> I am unclear as to the distinctions you need regarding the other two requested terms. Can you provide a bit more information on these?
> 
> Best regards, Darren

Dear Darren, 

I get your point. But I would say they are not the same. The terms "Fibrin" and "fibrinogen complex" are more acceptable as synonyms. Could you please review the terms once again and make a decision. And maybe you would like to have it as synonym. Please let me know about your decision.

Please consider to recheck "cytosolic creatine kinase complex, MB-type" and "cytosolic creatine kinase, MB".

Thank you!

**Comment by nataled** [comment]
Hi Astghik,
A few comments/questions:

- So far I cannot confirm that 'fibrin' and 'fibrinogen complex' refer to the same thing. I also cannot find anything (other than GO) that specifically states that 'fibrinogen complex' and 'fibrinogen' are the same (in GO, the latter is an exact synonym for the former). As mentioned previously, 'fibrinogen complex' appears to be some mixture of proteins. I suspect GO simply called it 'fibrinogen complex' because, well, it's a complex :) and that all three are actually different things. That being said, we know for sure that fibrin and fibrinogen are not the same, and we know for sure that the GO and PRO 'fibrinogen complex' terms are intended to be, specifically, fibrinogen, so adding 'fibrin' as a synonym would not make sense. If 'fibrin' is indeed called 'fibrinogen complex' in the literature, then the correct approach would be to change the GO and PRO names from 'fibrinogen complex' to 'fibrinogen'. I presume you have some literature resource that says 'fibrin' and 'fibrinogen complex' are the same? Can you provide that so I can review it? 
-  I have created the lipoprotein(a) term. Since it was easy to do so, I made both the generic version ("lipoprotein(a)", aka "Lp(a)"; PR:000085779) and the human-specific version ("lipoprotein(a) (human)", aka "Lp(a) (human)";PR:000085780). IMPORTANT NOTE: While these identifiers are usable and will resolve, they will not be available in the main PRO file until the next release, tentatively scheduled for January (though it is very likely we will make an early release, hopefully in December or maybe even earlier).
- I'm still not clear on your request about creatine kinase. Was it just to add synonyms? If so, I just added the following synonyms to both the parent and human-specific terms: 
```
Generic (PR:000027247)       Human (PR:000050356)
"CK-MB"                      "CK-MB (human)"
"CKMB"                       "CKMB (human)"
"creatine kinase MB"         "creatine kinase MB (human)"
"creatine kinase-MB"         "creatine kinase-MB (human)"
```
Let me know if there are other synonyms to add, or if there's a different thing you need.

**Comment by Astghik-S** [comment]
Dear Darren,

Thank you very much for the informative answer!
 - Wherever I met Fibrinogen term ist was never written as "fibrinogen complex". For instance, here https://pubmed.ncbi.nlm.nih.gov/15837518/ , in the definition "Fibrinogen is a large, **complex**, fibrous glycoprotein with three pairs of polypeptide chains linked together by 29 disulfide bonds. "  Correct me if I am mistaken,but as I understand the word "complex" is an adjective here and the term is called "fibrinogen" not "fibrinogen complex". So if zou prefer to keep the term "fibrinogan complex" then maybe it is a good idea to add "fibrinogen" as a synonym?
 
 - Thank you for creating lipoprotein(a) term. So it means we cannot yet use the term right?
 - The same issue with "creatine kinase MB". In the literature the term "creatine kinase MB" is commonly used and not   "creatine kinase MB complex ". So I think adding it as a synonym resolves the problem.

**Comment by nataled** [comment]
Dear Astghik,
- After further consideration, I've decided to change the name of 'fibrinogen complex (human)' to 'fibrinogen (human)'. I agree that 'fibrinogen' is the main term used, and we only kept it as 'fibrinogen complex' because that is the name of the complex in GO. Bear in mind that this change won't impact the GO term, but they already have 'fibrinogen' as a synonym.\
- You can use the 'lipoprotein(a)' term. You won't be able to do an import for it, so when you attempt to it won't have a name or anything associated with it (like parent term) until the PRO release. The purl http:/purl.obolibrary.org/obo/PR_000085779 will resolve now, however.
- If you come across any additional synonyms for terms you use that are in PRO, please let us know and we'll add them.

Thanks for using PRO! If you are satisfied that your needs are met, please go ahead and close this issue.

Best regards,
Darren

**Comment by Astghik-S** [comment]
Dear Darren,

Thank you very much! All good! I am closing the issue.

Best regards,
Astghik

**Comment by Astghik-S** [comment]
x
